FROM python:3.12-slim

WORKDIR /migrate

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY packages/common /packages/common
COPY packages/contracts /packages/contracts

RUN pip install --no-cache-dir /packages/common /packages/contracts

WORKDIR /packages/common

CMD ["alembic", "upgrade", "head"]
